[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "target-feature=+crt-static"]

[env]
# LEPTONICA_INCLUDE_PATH = { value = "C:\\my_projects\\my_rust_app\\vcpkg\\installed\\x64-windows-static\\include" }
# LEPTONICA_LINK_PATHS = { value = "C:\\my_projects\\my_rust_app\\vcpkg\\installed\\x64-windows-static\\lib" }
LEPTONICA_LINK_LIBS = { value = "leptonica-1.85.0" }
# TESSERACT_INCLUDE_PATHS = { value = "C:\\my_projects\\my_rust_app\\vcpkg\\installed\\x64-windows-static\\include" }
# TESSERACT_LINK_PATHS = { value = "C:\\my_projects\\my_rust_app\\vcpkg\\installed\\x64-windows-static\\lib" }
TESSERACT_LINK_LIBS = { value = "tesseract55" }
LIBCLANG_PATH = { value = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\Llvm\\x64\\bin" }
VCPKG_ROOT = { value = "C:\\Users\\dongchao\\Code\\deepindex\\vcpkg" }
DUCKDB_STATIC= { value = "1" }
