[env]
LEPTONICA_INCLUDE_PATH = {value = "C:\\Users\\dongchao\\Code\\deepindex\\vcpkg\\installed\\x64-windows\\include"}
LEPTONICA_LINK_PATHS = {value = "C:\\Users\\dongchao\\Code\\deepindex\\vcpkg\\installed\\x64-windows\\lib"}
LEPTONICA_LINK_LIBS = { value = "leptonica-1.85.0" }
TESSERACT_INCLUDE_PATHS = { value = "C:\\Users\\dongchao\\Code\\deepindex\\vcpkg\\installed\\x64-windows\\include" }
TESSERACT_LINK_PATHS = { value = "C:\\Users\\dongchao\\Code\\deepindex\\vcpkg\\installed\\x64-windows\\lib" }
TESSERACT_LINK_LIBS = { value = "tesseract55" }
LIBCLANG_PATH = { value = "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\Llvm\\x64\\bin" }

# VCPKG_ROOT = { value = "C:\\Users\\dongchao\\Code\\deepindex\\vcpkg" }
