name: Build on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clean
        run: |
          just clean

      - name: Cache vcpkg-pkgs
        id: cache-vcpkg-pkgs
        uses: actions/cache@v4
        with:
          path: |
            vcpkg_installed/x64-windows/bin
            vcpkg_installed/x64-windows/include
            vcpkg_installed/x64-windows/lib
          key: ${{ runner.os }}-vcpkg-pkgs-${{ hashFiles('vcpkg.json') }}-build

      - name: Run install-vcpkg-pkgs
        if: steps.cache-vcpkg-pkgs.outputs.cache-hit != 'true'
        run: |
          just install-vcpkg-pkgs

      - name: Run install-npm-pkgs
        run: |
          just install-npm-pkgs
      
      - run: rustup toolchain install stable --profile minimal
      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: 'src-tauri'

      - name: Run Build
        run: |
          just build

      - name: Run check
        run: |
          just check

      # - name: Run release
      #   run: |
      #     just release
