name: Build on Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: extractions/setup-just@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clean
        run: |
          just clean

      - name: Run install
        run: |
          just install

      - name: Run check
        run: |
          just check

      - name: Run release
        run: |
          just release
